In [27]:
import pandas as pd
from sklearn import datasets
import numpy as np
wine=datasets.load_wine()
x=wine.data
y=wine.target

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)

from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(max_depth=5)
classifier.fit(x_train_std,y_train)
y_pred=classifier.predict(x_test_std)
print("Missclassified sample : %d"%(y_test!=y_pred).sum())
   
    
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

print("Accuracy",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



Missclassified sample : 1
Accuracy 0.9722222222222222
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00         6

   micro avg       0.97      0.97      0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36

